### ISSUE TITLE
how to convert this es6 js to haxe?

### ISSUE THREAD

**Issue by sonygod** [haxiomic/dts2hx#20]
first .convert *.d.ts file to haxe extern.

1:it's include haxe's keyword.
2:how to define build.hxml?

Hello.js

      cc.Class({
          extends: cc.Component,

        properties: {
            label: {
                default: null,
                type: cc.Label
            },
            // defaults, set visually when attaching this script to the Canvas
            text: 'qestion'
        },

        // use this for initialization
        onLoad: function () {
            this.label.string = "1";
        },

        // called every frame
        update: function (dt) {

        },
    });

[creator.d.zip](https://github.com/haxiomic/dts2hx/files/4661854/creator.d.zip)

  I try to write some like this .but it's lot's of error.

    import global.Cc;
    import global.cc.*;
    @:expose
    class HelloWorld  {
        

        public static function main() {
            Cc.Class({
                extends_: cc.Component,
            
                properties: {
                    label: {
                        default_: null,
                        type: cc.Label
                    },
                    // defaults, set visually when attaching this script to the Canvas
                    text: 'qestion'
                },
            
                // use this for initialization
                onLoad: function () {
                    this.label.string = "1";
                },
            
                // called every frame
                update: function (dt) {
            
                },
            });
        }
    }

**Comment by sonygod** [comment]
and the typescript version is 

 const {ccclass, property} = cc._decorator; // 从 cc._decorator 命名空间中引入 ccclass 和 property 两个装饰器

@ccclass // 使用装饰器声明 CCClass
export default class NewClass extends cc.Component { // ES6 Class 声明语法，继承 cc.Component

    @property(cc.Label)     // 使用 property 装饰器声明属性，括号里是属性类型，装饰器里的类型声明主要用于编辑器展示
    label: cc.Label = null; // 这里是 TypeScript 用来声明变量类型的写法，冒号后面是属性类型，等号后面是默认值

    // 也可以使用完整属性定义格式
    @property({
        visible: false
    })
    text: string = 'hello';

    // 成员方法
    onLoad() {
        // init logic
    }
}

**Comment by haxiomic** [comment]
- For haxe keywords you can use quotes to wrap the field names, [in a future version of haxe this will be supported in autocomplete and type-checking too](https://github.com/HaxeFoundation/haxe/pull/9433).
- Haxe `this` is different from js-this, haxe this refers to the local class, whereas js this can be changed to refer to different things. So where you see `this` in javascript you need to use `js.Lib.nativeThis` to get the same behavior in haxe
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

You can convert the example pretty much directly
```haxe
import global.cc.Label;
import global.cc.Component;
import global.Cc;

class Main {

	static function main() {
		Cc.Class({
			'extends': Component,
			properties: {
				label: {
					'default': null,
					type: Label,
				},
				text: 'question',
			},

			onLoad: function() {
				var this_ = js.Lib.nativeThis;
				this_.lable.string = "1";
			},

			update: function (dt) {

			},
		});
	}

}
```
(I've confirmed the code compiles and the output is good)

I've made a slight improvement with function types so upgrade to 0.11.6 and you shouldn't have any errors

I generated creator externs with
`npx dts2hx ./helloworld-typescript/creator --tsconfig ./helloworld-typescript/tsconfig.json`

I appreciate feedback and bug reports, but I have a very limited time budget, please keep issues to just bugs you find in dts2hx and please put in the time to validate them because it takes away time from actually improving dts2hx

General haxe-extern help would be better asked at community.haxe.org

**Comment by sonygod** [comment]
Although it's work but it's not perfect,and haxe code have no type of label definition. Actually it's cc.Label.
