### ISSUE TITLE
typedefs and @:native/overload

### ISSUE THREAD

**Issue by ciscoheat** [haxiomic/dts2hx#55]
I've noticed that in some cases, `@:native` and `@:overload` are placed in a typedef, so they won't really be used. A quick fix is to make the typedef an external class instead.

**Comment by haxiomic** [comment]
This one is deliberate, unfortunately most of the time these cannot be converted to classes because we need structure type unification rules to apply, however right now haxe has no way to have a typedef with non-ascii fields, so some kinds of @:native-like approach is required there. Nakado has implemented support for @:native on typedef, if we're lucky it could arrive in 4.2, if it does then those fields with @:native will start working. There's no ideal work around and it's an ongoing talk in haxe on how best to resolve
See https://github.com/HaxeFoundation/haxe/pull/9433

**Comment by ciscoheat** [comment]
I see, for now I will convert those few classes to extern, it will be adequate for my needs at the moment. Thanks for the explanation.
